name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: devel
    env:
      REGISTRY: docker.io
      REPOSITORY: ${{ secrets.REPOSITORY }}
      REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
      REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}

    steps:
    - uses: actions/checkout@v4

    - name: ğŸš€ Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: ğŸ§Š Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: âš™ï¸ Install dependencies
      run: task setup

    - name: ğŸ”¨ Build
      run: task build

    - name: ğŸ” Test
      run: task test
