name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: devel
    env:
      REGISTRY: docker.io
      REPOSITORY: ${{ secrets.REPOSITORY }}
      REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
      REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}

    steps:
    - uses: actions/checkout@v4

    - name: ğŸš€ Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: âš™ï¸ Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y
        sudo apt-get install libbtrfs-dev -y
        sudo apt-get install libgpgme-dev -y

    - name: âš™ï¸ Mod Tidy
      run: go mod tidy

    - name: ğŸ”¨ Build
      run: go build -v ./...

    - name: ğŸ” Test
      run: go test -v ./...
