name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      ftp:
        image: fauria/vsftpd
        ports:
          - 21:21
          - 30000-30009:30000-30009
        options: >-
          --health-cmd "nc -zv localhost 21"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    environment: devel
    env:
      REGISTRY: docker.io
      REPOSITORY: ${{ secrets.REPOSITORY }}
      REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
      REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}

    steps:
    - uses: actions/checkout@v4

    #- name: ğŸš€ Set up Go
    #  uses: actions/setup-go@v4
    #  with:
     #   go-version: '1.22.3'

    #- name: ğŸ§Š Install Task
    #  uses: arduino/setup-task@v1
    #  with:
     #   version: 3.x
     #   repo-token: ${{ secrets.GITHUB_TOKEN }}

    #- name: âš™ï¸ Install dependencies
     # run: task setup

    #- name: ğŸ”¨ Build
     # run: task build

    - name: Wait for FTP server to be healthy
      run: |
        echo "Waiting for FTP server to start..."
        sleep 30
        until [ "$(docker inspect --format='{{.State.Health.Status}}' $(docker-compose ps -q ftp))" == "healthy" ]; do
          echo "Waiting for FTP server to be healthy..."
          sleep 10
        done

    #- name: ğŸ” Test
     # run: lftp -u testuser,password -e "ls; bye" ftp://localhost:21
